Implemention on Add and Remove button
CELYNEBIRUNGI/TO-DO-list pull request #2
Opened 2023-06-06 10:21 UTC by CELYNEBIRUNGI

Added Modules javascript files to src files

2023-06-06 11:24 UTC, AlphaNtihinduka requested changes
## Hi @CELYNEBIRUNGI 🙋‍♂️
Good job working on implementing addition and removal of todo list. You have done incredibly well. 👏  

TO HIGHLIGHT:
- The todolist item can be added ✔️ 
- The todolist items are stored in the localstorage✔️
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- _Kindly consider the inline review comments. ☺️._

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-06-06 11:24 UTC, AlphaNtihinduka commented on src/index.js
> +  });
- [ ] I have noticed that when a new todo list item is added, the item displays twice. Kindly verify the event Listeners usage to ensure that the todo list item is not double displayed ☺️.
- [ ] In addition, consider using the delete icon instead of dots. This will make your application a good user interface and also be more user friendly.

2023-06-06 14:27 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @CELYNEBIRUNGI 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 14:27 UTC, AbelG101 commented on src/modules/display.js
> +export default displayList;
- [ ] It seems like the issue mentioned previously still pertains as the `displayList()` function is getting called twice I've checked the local storage and there seems to be only 1 copy of each task, so It should be from the way the above function is getting called so please carefully debug it.
- Here's how it behaves
  ![firefox_0nyT0ZdEYt](https://github.com/CELYNEBIRUNGI/TO-DO-list/assets/104968236/a1de1263-b96c-480b-bfad-6d0dd54c17d8)

2023-06-07 07:12 UTC, peterrobert commented on src/modules/display.js
> +export default displayList;
This change has been implemented well

2023-06-07 07:13 UTC, peterrobert approved these changes
Hi @CELYNEBIRUNGI, 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️
[ ] Great work making the changes as requested by the previous reviewer✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 09:42 UTC, merged